server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/customer  #  connect to localhost:5432 to postgres db container
    password: 'password'                            #- database named 'customer'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true